calendars:
  - name: Timéo
    models:
      - name: normal
        days: >
          -+++ ++++ ++++ ++++ ++++ ++++ ++++
          ++++ ++++ ++++ ++++ +++- ---- ----
      - name: holidays
        days: >
          ---- ---- ---- ---- ---- ---- ---+
          ++++ ++++ ++++ ++++ ++++ ++++ ++++
      - name: summer_holidays
        days: >
          ---- ---- ---- ---- ---- ---- ----
          ---- ---- ---- ---- ---- ---- ---+
          ++++ ++++ ++++ ++++ ++++ ++++ ++++
          ++++ ++++ ++++ ++++ ++++ ++++ ++++
    periods:
      "2025-01-06": normal
      "2025-02-24": holidays
      "2025-03-10": normal
      "2025-04-21": holidays
      "2025-05-05": normal
      "2025-07-07": summer_holidays
      "2025-09-01": normal
      "2025-10-20": holidays
      "2025-03-11": normal
      "2025-12-22": holidays
      "2026-05-01": normal
      "2026-01-06": _end_
    exceptions:
      "2025-12-24": --++
      "2025-12-25": ++--
  - name: Jeanne
    models:
      - name: normal
        days: >
          ++++ ++++ ++++ ++++ +++- ---- ----
          ---- ---- ---- ---- ---+ ++++ ++++
      - name: holidays
        days: >
          ++++ ++++ ++++ ++++ +++- ---- ----
          ---- ---- ---- ---- ---+ ++++ ++++
      - name: summer_holidays
        days: >
          ---- ---- ---- ---- ---- ---- ----
          ---- ---- ---- ---- ---- ---- ---+
          ++++ ++++ ++++ ++++ ++++ ++++ ++++
          ++++ ++++ ++++ ++++ ++++ ++++ +++-
    periods:
      "2025-01-06": normal
      "2025-02-24": holidays
      "2025-03-10": normal
      "2025-04-21": holidays
      "2025-05-05": normal
      "2025-07-07": summer_holidays
      "2025-09-01": normal
      "2025-10-20": holidays
      "2025-03-11": normal
      "2025-12-22": holidays
      "2026-05-01": normal
      "2026-01-06": _end_
    exceptions:
      "2025-12-24": --++
      "2025-12-25": ++++
      "2025-12-31": --++
      "2026-01-01": ++--
  - name: Tom
    models:
      - name: normal
        days: >
          ++++ +++- ---- -+++ ++++ ++++ ++++
          +--- ---+ ++++ +--- ---- ---- ----
      - name: holidays
        days: >
          ++++ ++++ ++++ ++++ ++++ ++++ +++-
          ---- ---- ---- ---- ---- ---- ---+
      - name: summer_holidays
        days: >
          ---- ---- ---- ---- ---- ---- ----
          ---- ---- ---- ---- ---- ---- ---+
          ++++ ++++ ++++ ++++ ++++ ++++ ++++
          ++++ ++++ ++++ ++++ ++++ ++++ +++-
    periods:
      "2025-01-06": normal
      "2025-02-24": holidays
      "2025-03-10": normal
      "2025-04-21": holidays
      "2025-05-05": normal
      "2025-07-07": summer_holidays
      "2025-09-01": normal
      "2025-10-20": holidays
      "2025-03-11": normal
      "2025-12-22": holidays
      "2026-05-01": normal
      "2026-01-06": _end_
    exceptions:
      "2025-12-24": --++

important_days:
  "2025-12-25": "Xmas"
  "2025-12-24": "Xmas eve"
  "2025-09-11": "BD Dad"
  "2025-08-02": "BD Mum"
  "2025-08-29": "BD Tom"
  "2025-05-08": "BD Timéo"
  "2025-05-11": "BD Timéo"
  "2025-07-09": "BD Jeanne"
  "2025-12-31": "New year eve"
